name: build
on:
 push:
 pull_request:
 schedule:
#Every 5 days at midnight 
    - cron:  "0 0 1/5 * *"

jobs:
  
  #compilejobOSX-10-entrypoint1:
    #runs-on: macos-10.15
    #name: cascade_on_OSX10-entrypoint1
    #steps:
    #- name: Checkout
      #uses: actions/checkout@v2
    #- name: Compile
      #id: compile
      #run: ./.github/workflows/osx/entrypoint1.sh
    #- name: Get the output status
      #run: exit ${{ steps.compile.outputs.out }}
      
  #compilejobOSX-10-entrypoint2:
    #runs-on: macos-10.15
    #name: cascade_on_OSX10-entrypoint2
    #steps:
    #- name: Checkout
      #uses: actions/checkout@v2
    #- name: Compile
      #id: compile
      #run: ./.github/workflows/osx/entrypoint2.sh
    #- name: Get the output status
      #run: exit ${{ steps.compile.outputs.out }}


  compilejobOSX-11-entrypoint1:
    runs-on: macos-11
    name: cascade_on_OSX11-entrypoint1
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Compile
      id: compile
      run: ./.github/workflows/osx/entrypoint1.sh
    - name: Get the output status
      run: exit ${{ steps.compile.outputs.out }}
      
  compilejobOSX-11-entrypoint2:
    runs-on: macos-11
    name: cascade_on_OSX11-entrypoint2
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Compile
      id: compile
      run: ./.github/workflows/osx/entrypoint2.sh
    - name: Get the output status
      run: exit ${{ steps.compile.outputs.out }}
